1. Файл minutes_n_ingredients.csv содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива numpy типа int32, используя np.loadtxt. Выведите на экран первые 5 строк массива.

In [1]:
from numpy import *

data = loadtxt('minutes_n_ingredients.csv', delimiter=';', skiprows=1, dtype=int32) # skiprows с учётом того, что первая строка файла - заголовки

print(f"Первые 5-ть строк: \n{data[:5]}")

Первые 5-ть строк: 
[[ 1 34  3]
 [ 2 45  5]
 [ 3 12  6]
 [ 4 56 10]
 [ 5 78  3]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [2]:
import numpy as np

mean_ = mean(data[:, 1:], axis=0)
min_ = np.min(data[:, 1:], axis=0)
max_ = np.max(data[:, 1:], axis=0)
median_ = median(data[:, 1:], axis=0)

print(f"Среднее значение: {mean_}")
print(f"\nМинимальное значение: {min_}")
print(f"\nМаксимальное значение: {max_}")
print(f"\nМедиана: {median_}")

Среднее значение: [34.8125  5.375 ]

Минимальное значение: [0 2]

Максимальное значение: [90 10]

Медиана: [33.  5.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля q0.75.

In [3]:
q_75 = quantile(data[:, 1:], 0.75)
data[:, 1:] = minimum(data[:, 1:], q_75)

print(f"Значение квантиля: {q_75}")
# print(f"\nИзменённая база данных: \n{data}")

Значение квантиля: 32.5

Изменённая база данных: 
[[ 1 32  3]
 [ 2 32  5]
 [ 3 12  6]
 [ 4 32 10]
 [ 5 32  3]
 [ 6 32  2]
 [ 7 11  6]
 [ 8 23  7]
 [ 9 32  8]
 [10 32  4]
 [11  0  5]
 [12 19  3]
 [13  0  5]
 [ 2 32  5]
 [14 32  8]
 [ 7 11  6]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [4]:
zero_n = sum(data[:, 1] == 0)
data[:, 1] = where(data[:, 1] == 0, 1, data[:, 1])

print(f"Кол-во времени выполнений == 0: {zero_n}")
# print(f"\nИзменённая база данных: \n{data}")

Кол-во времени выполнений == 0: 2

Изменённая база данных: 
[[ 1 32  3]
 [ 2 32  5]
 [ 3 12  6]
 [ 4 32 10]
 [ 5 32  3]
 [ 6 32  2]
 [ 7 11  6]
 [ 8 23  7]
 [ 9 32  8]
 [10 32  4]
 [11  1  5]
 [12 19  3]
 [13  1  5]
 [ 2 32  5]
 [14 32  8]
 [ 7 11  6]]


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [200]:
unique_ = unique(data, axis=0)
n_unique = unique_.shape[0]

print(f"Кол-во уникальных рецептов: {n_unique}")

Кол-во уникальных рецептов: 14


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [175]:
unique_i = unique(data[:, 2])
n_unique_i = unique_i.size

print(f"Кол-во уникальных кол-в ингредиентов: {n_unique_i}")
print(f"Уникальные значения кол-в ингредиентов: {unique_i}")

Кол-во уникальных кол-в ингредиентов: 8
Уникальные значения кол-в ингредиентов: [ 2  3  4  5  6  7  8 10]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [176]:
filtered_data = data[where(data[:, 2] <= 5)]

# print(f"Новая версия базы данных: \n{filtered_data}")

Новая версия базы данных: 
[[ 1 32  3]
 [ 2 32  5]
 [ 5 32  3]
 [ 6 32  2]
 [10 32  4]
 [11  1  5]
 [12 19  3]
 [13  1  5]
 [ 2 32  5]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета.

In [177]:
mean_i_div_t = divide(data[:, 2], data[:, 1])
max_mean_i_div_t = max(mean_i_div_t)

print(f"Среднее кол-во ингредиентов на минуту рецепта: \n{mean_i_div_t}")
print(f"Max среднее кол-во ингредиентов на минуту рецепта: {max_mean_i_div_t}")  

Среднее кол-во ингредиентов на минуту рецепта: 
[0.09375    0.15625    0.5        0.3125     0.09375    0.0625
 0.54545455 0.30434783 0.25       0.125      5.         0.15789474
 5.         0.15625    0.25       0.54545455]
Max среднее кол-во ингредиентов на минуту рецепта: 5.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью.

In [178]:
top_100 = argsort(data[:, 1])[-100:]

mean_i_top_100 = mean(data[top_100, 2])
print(f"Среднее кол-во ингредиентов для топ-100 рецептов с наибольшим временем выполнения: \n{mean_i_top_100}")

Среднее кол-во ингредиентов для топ-100 рецептов с наибольшим временем выполнения: 
5.375


10. Выберите случайным образом и выведите информацию о 10 различных рецептах.

In [194]:
rng = np.random.default_rng()
print(f"Информация о 10-ти случайных рецептах: \n{rng.choice(data, 10, replace=False)}")

Информация о 10-ти случайных рецептах: 
[[ 7 11  6]
 [ 8 23  7]
 [10 32  4]
 [ 1 32  3]
 [11  1  5]
 [ 5 32  3]
 [ 4 32 10]
 [ 3 12  6]
 [14 32  8]
 [ 7 11  6]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [180]:
mean_i = mean(data[:, 2])

print("Процент рецептов, кол-во ингредиентов в которых ниже среднего: {:.1%}".format((data < mean_i).mean()))

Процент рецептов, кол-во ингредиентов в которых ниже среднего: 35.4%


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [181]:
new_data = np.append(data, zeros((len(data), 1), dtype=int), axis=1)
new_data[:, 3] = where((data[:, 1] <= 20) & (data[:, 2] <= 5), 1, 0)

# print(f"Обновлённая база данных с колонкой о простоте рецепта: \n{new_data}")

Обновлённая база данных с колонкой о простоте рецепта: 
[[ 1 32  3  0]
 [ 2 32  5  0]
 [ 3 12  6  0]
 [ 4 32 10  0]
 [ 5 32  3  0]
 [ 6 32  2  0]
 [ 7 11  6  0]
 [ 8 23  7  0]
 [ 9 32  8  0]
 [10 32  4  0]
 [11  1  5  1]
 [12 19  3  1]
 [13  1  5  1]
 [ 2 32  5  0]
 [14 32  8  0]
 [ 7 11  6  0]]


13. Выведите процент "простых" рецептов в датасете.

In [182]:
print("Процент простых рецептов: {:.1%}".format((new_data[:, 3] == 1).mean()))

Процент простых рецептов: 18.8%


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [7]:
short_ = data[data[:, 1] < 10]
standard_ = data[(data[:, 1] >= 10) & (data[:, 1] < 20)]
long_ = data[data[:, 1] >= 20]

size_n = min(short_.shape[0], standard_.shape[0], long_.shape[0])

short_ = short_[:size_n]
standard_ = standard_[:size_n]
long_ = long_[:size_n]

new_3d_data = np.append(short_, standard_)
new_3d_data = np.append(new_3d_data, long_)

new_3d_data.shape = 3, size_n, 3

print(f"Форма массива: \n{new_3d_data.shape}")
# print(f"Трёхмерный массив: \n{new_3d_data}")

Форма массива: 
(3, 2, 3)

Трёхмерный массив: 
[[[11  1  5]
  [13  1  5]]

 [[ 3 12  6]
  [ 7 11  6]]

 [[ 1 32  3]
  [ 2 32  5]]]
